package com.ecnav.ficharpg.util;

public class Util
{
    public static final String CHARACTER_ID = "character_id";
    public static final String NAME_REPLY = "name_reply";
    public static final String CLASS_REPLY = "class_reply";
    public static final String SUBCLASS_REPLY = "subclass_reply";
    public static final String LEVEL_REPLY = "level_reply";
    public static final String RACE_REPLY = "race_reply";
    public static final String BACKGROUND_REPLY = "background_reply";
    public static final String ALIGNMENT_REPLY = "alignment_reply";
    public static final String HITPOINTS_REPLY = "hitpoints_reply";
    public static final String ARMORCLASS_REPLY = "armorclass_reply";
    public static final String INITIATIVE_REPLY = "initiative_reply";
    public static final String SHEETTYPE = "sheet_type";
    public static final String DEX_REPLY = "dex_reply";
    public static final String STR_REPLY = "str_reply";
    public static final String CON_REPLY = "con_reply";
    public static final String INT_REPLY = "int_reply";
    public static final String WIS_REPLY = "wis_reply";
    public static final String CHA_REPLY = "cha_reply";
    public static final String PRO_REPLY = "pro_reply";
    public static final String SPEED_REPLY = "speed_reply";
    public static final String QUERY_SEARCH = "query_search";
    public static final int DUNGEONS_AND_DRAGONS = 1;
    public static final int TORMENTA = 2;
    public static final String PARAMETER_FOR_FRAGMENT = "parameter";
    public static final String CLASS_ID = "class_id";
    public static final String CHOSEN_CLASS_BOOLEAN = "chosen_class_boolean";
    public static final String CHOSEN_CLASS_ID = "chosen_class_id";
    public static final String CLASS_OR_SUBCLASS = "class_or_subclass";
    public static final String FEATURE_LEVEL = "feature_level";
    public static final String FEATURE_NAME = "feature_bane";
    public static final String FEATURE_DESCRIPTION = "feature_description";
    public static final int CLASS_INFO_FLAG = 1;
    public static final int SUBCLASS_INFO_FLAG = 2;
    public static final String EQUIP_NAME = "equip_name";
    public static final String EQUIP_DESCRIPTION = "equip_description";
    public static final String EQUIP_TYPE = "equip_type";
    public static final String EQUIP_AMOUNT = "equip_amount";
    public static final String EQUIP_USAGES = "equip_usages";
    public static final String EQUIP_DAMAGE = "equip_damage";
    public static final String EQUIP_ATTACK = "equip_attack";
    public static final int SHOW_FEATURE_IN_CHARACTER = 1;
    public static final int CLASS_AND_SUBCLASS_CHOOSER = 2;
    public static final String SPELL_NAME = "spell_name";
    public static final String SPELL_LEVEL = "spell_level";
    public static final String SPELL_DESCRIPTION = "spell_description";
    public static final String SPELL_SOMATIC = "spell_somatic";
    public static final String SPELL_VERBAL = "spell_verbal";
    public static final String SPELL_MATERIAL = "spell_material";
    public static final String SPELL_COMPONENTS = "spell_components";
}
